"""Chenxin

Revision ID: 22bfc16bc922
Revises: 2149ac29fedd
Create Date: 2017-10-14 16:17:03.462000

"""

# revision identifiers, used by Alembic.
revision = '22bfc16bc922'
down_revision = '2149ac29fedd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###
